#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
RUN_ID="${RUN_ID:-$(date +%Y%m%d_%H%M%S)}"
export RUN_ID
export MODELS="${MODELS:-patchtst}"
export OUT_ROOT="${OUT_ROOT:-OFP_DL_official_results/lookback24h_ahead1h_patchtst_${RUN_ID}}"
export EPOCHS="${EPOCHS:-3}"
export BATCH_SIZE="${BATCH_SIZE:-128}"
export SEQ_LEN="${SEQ_LEN:-288}"
export INPUT_MODE="${INPUT_MODE:-model2_features}"
export NEGATIVE_RATIO="${NEGATIVE_RATIO:-10}"
export TRAIN_SAMPLING="${TRAIN_SAMPLING:-module_balanced}"
export AUX_BCE_WEIGHT="${AUX_BCE_WEIGHT:-0.3}"
export EVENT_LOSS_WEIGHT="${EVENT_LOSS_WEIGHT:-1.0}"
export EVENT_HIT_MODE="${EVENT_HIT_MODE:-primary_window}"
export EVENT_MODULES_PER_EPOCH="${EVENT_MODULES_PER_EPOCH:-96}"
export EVENT_MAX_WINDOWS_PER_MODULE="${EVENT_MAX_WINDOWS_PER_MODULE:-96}"
export MODULE_POSITIVE_WINDOWS_PER_MODULE="${MODULE_POSITIVE_WINDOWS_PER_MODULE:-32}"
export MODULE_NEGATIVE_WINDOWS_PER_FAULTY_MODULE="${MODULE_NEGATIVE_WINDOWS_PER_FAULTY_MODULE:-8}"
export MODULE_NORMAL_WINDOWS_PER_MODULE="${MODULE_NORMAL_WINDOWS_PER_MODULE:-8}"
export INDEX_VAL_FRACTION="${INDEX_VAL_FRACTION:-0.1}"
export SELECTION_METRIC="${SELECTION_METRIC:-f1_score}"
export POS_WEIGHT_CAP="${POS_WEIGHT_CAP:-20}"
export LR="${LR:-0.0003}"
export AMP="${AMP:-0}"

bash "$SCRIPT_DIR/run_first_warning_suite.sh"
